

export const ProductData = [
  {
    id: 1,
    name: "Squash - Guords",
    description: "Percu nephrostmy w frag",
    location: "Alaska",
    image: "http://dummyimage.com/121x103.png/dddddd/000000",
  },
  {
    id: 2,
    name: "Glass Clear 7 Oz Xl",
    description: "Male genital x-ray NEC",
    location: "Alaska",
    image: "http://dummyimage.com/127x176.png/5fa2dd/ffffff",
  },
  {
    id: 3,
    name: "Veal - Ground",
    description: "Punctum repair NEC",
    location: "Alaska",
    image: "http://dummyimage.com/151x238.png/5fa2dd/ffffff",
  },
  {
    id: 4,
    name: "Beef - Prime Rib Aaa",
    description: "Plastic rep ext ear NEC",
    location: "Alaska",
    image: "http://dummyimage.com/181x143.png/dddddd/000000",
  },
  {
    id: 5,
    name: "Chickhen - Chicken Phyllo",
    description: "Open red-sep epiphy NOS",
    location: "Alaska",
    image: "http://dummyimage.com/207x194.png/dddddd/000000",
  },
  {
    id: 6,
    name: "Bread - Raisin Walnut Oval",
    description: "Atmos press/compos contr",
    location: "Alaska",
    image: "http://dummyimage.com/132x109.png/cc0000/ffffff",
  },
  {
    id: 7,
    name: "Sugar Thermometer",
    description: "Finger amputation",
    location: "Alaska",
    image: "http://dummyimage.com/149x194.png/dddddd/000000",
  },
  {
    id: 8,
    name: "Tea - Jasmin Green",
    description: "Inser bone stim-meta/tar",
    location: "Alaska",
    image: "http://dummyimage.com/160x196.png/ff4444/ffffff",
  },
  {
    id: 9,
    name: "Bar - Granola Trail Mix Fruit Nut",
    description: "Incision uterine septum",
    location: "Alaska",
    image: "http://dummyimage.com/200x206.png/dddddd/000000",
  },
  {
    id: 10,
    name: "Beef - Cow Feet Split",
    description: "Perc mtrl vlv repr w imp",
    location: "Alaska",
    image: "http://dummyimage.com/138x245.png/cc0000/ffffff",
  },
  {
    id: 11,
    name: "Yogurt - Strawberry, 175 Gr",
    description: "Bicycle ergometer test",
    location: "Alaska",
    image: "http://dummyimage.com/153x224.png/5fa2dd/ffffff",
  },
  {
    id: 12,
    name: "Muffin Batt - Blueberry Passion",
    description: "Repl cardiodefib genratr",
    location: "Alaska",
    image: "http://dummyimage.com/249x156.png/cc0000/ffffff",
  },
  {
    id: 13,
    name: "Muffin Hinge - 211n",
    description: "Packed cell transfusion",
    location: "Alaska",
    image: "http://dummyimage.com/237x124.png/ff4444/ffffff",
  },
  {
    id: 14,
    name: "Oil - Shortening,liqud, Fry",
    description: "Hip surface, cermc/cermc",
    location: "Alaska",
    image: "http://dummyimage.com/144x243.png/ff4444/ffffff",
  },
  {
    id: 15,
    name: "Flour - Chickpea",
    description: "Facilit intraoc circ NEC",
    location: "Alaska",
    image: "http://dummyimage.com/118x238.png/dddddd/000000",
  },
  {
    id: 16,
    name: "Molasses - Fancy",
    description: "Induct labor-rupt memb",
    location: "Alaska",
    image: "http://dummyimage.com/116x107.png/cc0000/ffffff",
  },
  {
    id: 17,
    name: "Paper Cocktail Umberlla 80 - 180",
    description: "Lid marg lac rx-part th",
    location: "Alaska",
    image: "http://dummyimage.com/208x240.png/cc0000/ffffff",
  },
  {
    id: 18,
    name: "Soup - Campbells, Creamy",
    description: "Facial bone incision NEC",
    location: "Alaska",
    image: "http://dummyimage.com/228x123.png/5fa2dd/ffffff",
  },
  {
    id: 19,
    name: "Sobe - Tropical Energy",
    description: "Disarticulation of knee",
    location: "Alaska",
    image: "http://dummyimage.com/150x189.png/5fa2dd/ffffff",
  },
  {
    id: 20,
    name: "Table Cloth 54x72 White",
    description: "Other cast application",
    location: "Alaska",
    image: "http://dummyimage.com/144x192.png/ff4444/ffffff",
  },
  {
    id: 21,
    name: "Sauerkraut",
    description: "Wedge osteotomy NOS",
    location: "Alaska",
    image: "http://dummyimage.com/217x219.png/cc0000/ffffff",
  },
  {
    id: 22,
    name: "Sour Puss - Tangerine",
    description: "Transab lg bowel endosc",
    location: "Alaska",
    image: "http://dummyimage.com/220x162.png/ff4444/ffffff",
  },
  {
    id: 23,
    name: "Bar Energy Chocchip",
    description: "Electromyography",
    location: "Alaska",
    image: "http://dummyimage.com/128x194.png/5fa2dd/ffffff",
  },
  {
    id: 24,
    name: "Coconut Milk - Unsweetened",
    description: "Parasitology-eye",
    location: "Alaska",
    image: "http://dummyimage.com/113x189.png/5fa2dd/ffffff",
  },
  {
    id: 25,
    name: "Wine - Cousino Macul Antiguas",
    description: "Scleral fistula repair",
    location: "Alaska",
    image: "http://dummyimage.com/204x235.png/cc0000/ffffff",
  },
  {
    id: 26,
    name: "Port - 74 Brights",
    description: "Reclose post op disrupt",
    location: "Alaska",
    image: "http://dummyimage.com/132x200.png/dddddd/000000",
  },
  {
    id: 27,
    name: "Sugar - Fine",
    description: "Closed rectal biopsy",
    location: "Alaska",
    image: "http://dummyimage.com/133x105.png/ff4444/ffffff",
  },
  {
    id: 28,
    name: "Crab - Blue, Frozen",
    description: "Ethmoidotomy",
    location: "Alaska",
    image: "http://dummyimage.com/182x140.png/5fa2dd/ffffff",
  },
  {
    id: 29,
    name: "Wine - Fino Tio Pepe Gonzalez",
    description: "Remov trunk device NEC",
    location: "Alaska",
    image: "http://dummyimage.com/158x178.png/dddddd/000000",
  },
  {
    id: 30,
    name: "Wine - Casablanca Valley",
    description: "Detach retina-diathermy",
    location: "Alaska",
    image: "http://dummyimage.com/150x116.png/dddddd/000000",
  },
  {
    id: 31,
    name: "Wine - Barolo Fontanafredda",
    description: "Removal of FB NOS",
    location: "Alaska",
    image: "http://dummyimage.com/106x142.png/ff4444/ffffff",
  },
  {
    id: 32,
    name: "Frangelico",
    description: "Cl reduct malar/zygo fx",
    location: "Alaska",
    image: "http://dummyimage.com/127x183.png/cc0000/ffffff",
  },
  {
    id: 33,
    name: "Pickle - Dill",
    description: "Lacrimal sys dx proc NEC",
    location: "Alaska",
    image: "http://dummyimage.com/248x189.png/cc0000/ffffff",
  },
  {
    id: 34,
    name: "Vodka - Hot, Lnferno",
    description: "Open reduc-dislocat NOS",
    location: "Alaska",
    image: "http://dummyimage.com/229x215.png/dddddd/000000",
  },
  {
    id: 35,
    name: "Marzipan 50/50",
    description: "Culture-eye",
    location: "Alaska",
    image: "http://dummyimage.com/107x105.png/cc0000/ffffff",
  },
  {
    id: 36,
    name: "Rice - Wild",
    description: "Transab proctosigmoidosc",
    location: "Alaska",
    image: "http://dummyimage.com/226x113.png/ff4444/ffffff",
  },
  {
    id: 37,
    name: "Oyster - In Shell",
    description: "Revise disc prosth NOS",
    location: "Alaska",
    image: "http://dummyimage.com/149x199.png/ff4444/ffffff",
  },
  {
    id: 38,
    name: "Pie Shell - 9",
    description: "Abd vein resect & anast",
    location: "Alaska",
    image: "http://dummyimage.com/156x235.png/ff4444/ffffff",
  },
  {
    id: 39,
    name: "Nougat - Paste / Cream",
    description: "X-ray of gravid uterus",
    location: "Alaska",
    image: "http://dummyimage.com/154x203.png/cc0000/ffffff",
  },
  {
    id: 40,
    name: "Syrup - Monin - Granny Smith",
    description: "Piercing of ear lobe",
    location: "Alaska",
    image: "http://dummyimage.com/181x135.png/dddddd/000000",
  },
  {
    id: 41,
    name: "Chicken - Whole Fryers",
    description: "Cranial puncture NEC",
    location: "Alaska",
    image: "http://dummyimage.com/139x213.png/ff4444/ffffff",
  },
  {
    id: 42,
    name: "Beer - Guiness",
    description: "Other tracheal operation",
    location: "Alaska",
    image: "http://dummyimage.com/117x118.png/5fa2dd/ffffff",
  },
  {
    id: 43,
    name: "Cranberries - Dry",
    description: "Hip joint biopsy",
    location: "Alaska",
    image: "http://dummyimage.com/155x114.png/ff4444/ffffff",
  },
  {
    id: 44,
    name: "Cake - Dulce De Leche",
    description: "Esophagoscopy NEC",
    location: "Alaska",
    image: "http://dummyimage.com/145x249.png/5fa2dd/ffffff",
  },
  {
    id: 45,
    name: "Shallots",
    description: "Nasal sinus fistula clos",
    location: "Alaska",
    image: "http://dummyimage.com/158x120.png/5fa2dd/ffffff",
  },
  {
    id: 46,
    name: "Beef - Outside, Round",
    description: "Other hernia repair",
    location: "Alaska",
    image: "http://dummyimage.com/163x249.png/ff4444/ffffff",
  },
  {
    id: 47,
    name: "Steam Pan - Half Size Deep",
    description: "Hand soft tissue exc NEC",
    location: "Alaska",
    image: "http://dummyimage.com/171x184.png/dddddd/000000",
  },
  {
    id: 48,
    name: "Pork - Ham, Virginia",
    description: "Repl joint of foot, toe",
    location: "Alaska",
    image: "http://dummyimage.com/134x217.png/cc0000/ffffff",
  },
  {
    id: 49,
    name: "Mushroom - Morels, Dry",
    description: "Delay opening colostomy",
    location: "Alaska",
    image: "http://dummyimage.com/138x162.png/ff4444/ffffff",
  },
  {
    id: 50,
    name: "Cake Circle, Foil, Scallop",
    description: "Procedure-three vessels",
    location: "Alaska",
    image: "http://dummyimage.com/143x245.png/ff4444/ffffff",
  },
  {
    id: 51,
    name: "Ecolab - Orange Frc, Cleaner",
    description: "Remov skel musc stimulat",
    location: "Alaska",
    image: "http://dummyimage.com/156x103.png/ff4444/ffffff",
  },
  {
    id: 52,
    name: "Red Cod Fillets - 225g",
    description: "Other glossotomy",
    location: "Alaska",
    image: "http://dummyimage.com/107x233.png/5fa2dd/ffffff",
  },
  {
    id: 53,
    name: "Wine - White, Pinot Grigio",
    description: "Frontal sinusectomy",
    location: "Alaska",
    image: "http://dummyimage.com/178x206.png/5fa2dd/ffffff",
  },
  {
    id: 54,
    name: "Wine - Soave Folonari",
    description: "Up limb sft tis xray NEC",
    location: "Alaska",
    image: "http://dummyimage.com/106x200.png/ff4444/ffffff",
  },
  {
    id: 55,
    name: "Steel Wool S.o.s",
    description: "Below knee amputat NEC",
    location: "Alaska",
    image: "http://dummyimage.com/210x212.png/dddddd/000000",
  },
  {
    id: 56,
    name: "Truffle - Whole Black Peeled",
    description: "Thoracic spine x-ray NEC",
    location: "Alaska",
    image: "http://dummyimage.com/213x242.png/cc0000/ffffff",
  },
  {
    id: 57,
    name: "Compound - Pear",
    description: "Parasitology-lower resp",
    location: "Alaska",
    image: "http://dummyimage.com/129x141.png/cc0000/ffffff",
  },
  {
    id: 58,
    name: "Appetizer - Asian Shrimp Roll",
    description: "CAS w fluoroscopy",
    location: "Alaska",
    image: "http://dummyimage.com/164x169.png/5fa2dd/ffffff",
  },
  {
    id: 59,
    name: "Liquid Aminios Acid - Braggs",
    description: "Transsac rectosigmoidect",
    location: "Alaska",
    image: "http://dummyimage.com/191x107.png/dddddd/000000",
  },
  {
    id: 60,
    name: "Lobak",
    description: "Carporadial fusion",
    location: "Alaska",
    image: "http://dummyimage.com/244x196.png/cc0000/ffffff",
  },
  {
    id: 61,
    name: "Wine - Two Oceans Cabernet",
    description: "Other chordotomy",
    location: "Alaska",
    image: "http://dummyimage.com/101x236.png/ff4444/ffffff",
  },
  {
    id: 62,
    name: "Carrots - Mini Red Organic",
    description: "Contrast arthrogram",
    location: "Alaska",
    image: "http://dummyimage.com/130x200.png/dddddd/000000",
  },
  {
    id: 63,
    name: "Tart - Butter Plain Squares",
    description: "Inject into thorax cavit",
    location: "Alaska",
    image: "http://dummyimage.com/231x128.png/ff4444/ffffff",
  },
  {
    id: 64,
    name: "Bananas",
    description: "Ven cath renal dialysis",
    location: "Alaska",
    image: "http://dummyimage.com/213x110.png/5fa2dd/ffffff",
  },
  {
    id: 65,
    name: "Lid - Translucent, 3.5 And 6 Oz",
    description: "Total pinealectomy",
    location: "Alaska",
    image: "http://dummyimage.com/210x130.png/ff4444/ffffff",
  },
  {
    id: 66,
    name: "Longos - Chicken Wings",
    description: "Subtotal mastectomy",
    location: "Alaska",
    image: "http://dummyimage.com/184x173.png/5fa2dd/ffffff",
  },
  {
    id: 67,
    name: "Pepper - Black, Whole",
    description: "Re-entry operation",
    location: "Alaska",
    image: "http://dummyimage.com/167x161.png/dddddd/000000",
  },
  {
    id: 68,
    name: "Transfer Sheets",
    description: "Eswl other sites",
    location: "Alaska",
    image: "http://dummyimage.com/245x132.png/dddddd/000000",
  },
  {
    id: 69,
    name: "Spice - Onion Powder Granulated",
    description: "Excise conjunctiv lesion",
    location: "Alaska",
    image: "http://dummyimage.com/208x210.png/dddddd/000000",
  },
  {
    id: 70,
    name: "Bagel - 12 Grain Preslice",
    description: "Biliary tract x-ray NEC",
    location: "Alaska",
    image: "http://dummyimage.com/213x160.png/cc0000/ffffff",
  },
  {
    id: 71,
    name: "Soup Campbells Split Pea And Ham",
    description: "Suture peptic ulcer NOS",
    location: "Alaska",
    image: "http://dummyimage.com/230x215.png/cc0000/ffffff",
  },
  {
    id: 72,
    name: "Cake - Miini Cheesecake Cherry",
    description: "Percut tunica aspiration",
    location: "Alaska",
    image: "http://dummyimage.com/220x153.png/cc0000/ffffff",
  },
  {
    id: 73,
    name: "Soup - French Onion, Dry",
    description: "Loc exc bone lesion NOS",
    location: "Alaska",
    image: "http://dummyimage.com/208x233.png/ff4444/ffffff",
  },
  {
    id: 74,
    name: "Fruit Salad Deluxe",
    description: "Suture urethral lacerat",
    location: "Alaska",
    image: "http://dummyimage.com/149x146.png/5fa2dd/ffffff",
  },
  {
    id: 75,
    name: "Container - Clear 32 Oz",
    description: "Therapeu erythropheresis",
    location: "Alaska",
    image: "http://dummyimage.com/205x164.png/ff4444/ffffff",
  },
  {
    id: 76,
    name: "Dill Weed - Fresh",
    description: "Total abd hyst NEC/NOS",
    location: "Alaska",
    image: "http://dummyimage.com/112x107.png/5fa2dd/ffffff",
  },
  {
    id: 77,
    name: "Juice - Grapefruit, 341 Ml",
    description: "Rep recur shlder disloc",
    location: "Alaska",
    image: "http://dummyimage.com/185x105.png/ff4444/ffffff",
  },
  {
    id: 78,
    name: "Wine - Fontanafredda Barolo",
    description: "Male genital x-ray NEC",
    location: "Alaska",
    image: "http://dummyimage.com/246x197.png/5fa2dd/ffffff",
  },
  {
    id: 79,
    name: "Water - Tonic",
    description: "Salivary operation NEC",
    location: "Alaska",
    image: "http://dummyimage.com/230x157.png/5fa2dd/ffffff",
  },
  {
    id: 80,
    name: "Piping - Bags Quizna",
    description: "Thorac lg bowel interpos",
    location: "Alaska",
    image: "http://dummyimage.com/163x228.png/dddddd/000000",
  },
  {
    id: 81,
    name: "Wakami Seaweed",
    description: "Thoracostomy closure",
    location: "Alaska",
    image: "http://dummyimage.com/223x201.png/dddddd/000000",
  },
  {
    id: 82,
    name: "Coffee - Ristretto Coffee Capsule",
    description: "Toxicology-lower urinary",
    location: "Alaska",
    image: "http://dummyimage.com/104x209.png/ff4444/ffffff",
  },
  {
    id: 83,
    name: "Green Scrubbie Pad H.duty",
    description: "Extracorpor hepat Assis",
    location: "Alaska",
    image: "http://dummyimage.com/183x137.png/dddddd/000000",
  },
  {
    id: 84,
    name: "Potatoes - Idaho 100 Count",
    description: "Endomet synechiae divis",
    location: "Alaska",
    image: "http://dummyimage.com/129x226.png/5fa2dd/ffffff",
  },
  {
    id: 85,
    name: "Chips Potato Swt Chilli Sour",
    description: "Create septal defect",
    location: "Alaska",
    image: "http://dummyimage.com/165x177.png/5fa2dd/ffffff",
  },
  {
    id: 86,
    name: "Macaroons - Two Bite Choc",
    description: "Skin & subq dx proc NEC",
    location: "Alaska",
    image: "http://dummyimage.com/154x200.png/ff4444/ffffff",
  },
  {
    id: 87,
    name: "Lotus Leaves",
    description: "Rabies vaccination",
    location: "Alaska",
    image: "http://dummyimage.com/177x184.png/dddddd/000000",
  },
  {
    id: 88,
    name: "Cake - Box Window 10x10x2.5",
    description: "Int insert 1-cham, non",
    location: "Alaska",
    image: "http://dummyimage.com/235x173.png/ff4444/ffffff",
  },
  {
    id: 89,
    name: "Wheat - Soft Kernal Of Wheat",
    description: "Cl fx reduc-femur",
    location: "Alaska",
    image: "http://dummyimage.com/201x165.png/5fa2dd/ffffff",
  },
  {
    id: 90,
    name: "Onion Powder",
    description: "Remove ureteral stimulat",
    location: "Alaska",
    image: "http://dummyimage.com/177x195.png/dddddd/000000",
  },
  {
    id: 91,
    name: "Oranges",
    description: "Open gastric biopsy",
    location: "Alaska",
    image: "http://dummyimage.com/145x168.png/ff4444/ffffff",
  },
  {
    id: 92,
    name: "Placemat - Scallop, White",
    description: "Electrocochleography",
    location: "Alaska",
    image: "http://dummyimage.com/237x100.png/ff4444/ffffff",
  },
  {
    id: 93,
    name: "Mix Pina Colada",
    description: "Manual exam of breast",
    location: "Alaska",
    image: "http://dummyimage.com/124x240.png/ff4444/ffffff",
  },
  {
    id: 94,
    name: "Tea - Decaf Lipton",
    description: "Revis bile tract anastom",
    location: "Alaska",
    image: "http://dummyimage.com/179x143.png/dddddd/000000",
  },
  {
    id: 95,
    name: "Coffee - Colombian, Portioned",
    description: "Tu remov ureter obstruct",
    location: "Alaska",
    image: "http://dummyimage.com/239x188.png/ff4444/ffffff",
  },
  {
    id: 96,
    name: "Cloves - Whole",
    description: "Limited consultation",
    location: "Alaska",
    image: "http://dummyimage.com/155x238.png/5fa2dd/ffffff",
  },
  {
    id: 97,
    name: "Wine - Red, Marechal Foch",
    description: "Arbovirus vaccinat NEC",
    location: "Alaska",
    image: "http://dummyimage.com/136x144.png/ff4444/ffffff",
  },
  {
    id: 98,
    name: "Wheat - Soft Kernal Of Wheat",
    description: "Dx ultrasound-thorax NEC",
    location: "Alaska",
    image: "http://dummyimage.com/193x234.png/ff4444/ffffff",
  },
  {
    id: 99,
    name: "Sour Puss - Tangerine",
    description: "Reopen laminectomy site",
    location: "Alaska",
    image: "http://dummyimage.com/141x192.png/ff4444/ffffff",
  },
  {
    id: 100,
    name: "Ecolab Silver Fusion",
    description: "Implantable hrt assist",
    location: "Alaska",
    image: "http://dummyimage.com/129x122.png/ff4444/ffffff",
  },
];
